name: ls to JSON
description: ls to JSON
branding:
  icon: 'code'  
  color: 'blue'
inputs:
  path:
    description: Path
    required: true
    default: .
  dotfiles:
    description: Include dotfiles
    required: false
    default: false
outputs:
  json:
    description: JSON
    value: ${{ steps.ls.outputs.json }}
runs:
  using: composite
  steps:
    - run: jq --version
      shell: bash
    - id: ls
      run: |
        json=$(ls ${options} | jq -Rsc 'split("\n")[:-1]')
        echo "${json}"
        echo "json=${json}" >> $GITHUB_OUTPUT
      shell: bash
      working-directory: ${{ inputs.path }}
      env:
        options: ${{ inputs.dotfiles == 'true' && '-A' || '' }}
