name: ls
description: ls to JSON
branding:
  icon: 'code'  
  color: 'blue'
inputs:
  path:
    description: path
    required: true
    default: .
outputs:
  json:
    description: JSON
    value: ${{ steps.ls.outputs.json }}
runs:
  using: composite
  steps:
    - run: jq --version
      shell: bash
    - id: ls
      run: |
        json=$(ls ${path} | jq -Rsc 'split("\n")[:-1]')
        echo "${json}"
        echo "json=${json}" >> $GITHUB_OUTPUT
      shell: bash
      env:
        path: ${{ inputs.path }}
