name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04, ubuntu-20.04, windows-2022, windows-2019, macos-12, macos-11 ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      - id: ls
        uses: ./
      - run: test "${json}" = '["LICENSE","README.md","action.yml"]'
        env:
          json: ${{ steps.ls.outputs.json }}
        if: ${{ runner.os != 'Windows' }}
      - run: test $Env:json = '["LICENSE","README.md","action.yml"]'
        env:
          json: ${{ steps.ls.outputs.json }}
        if: ${{ runner.os == 'Windows' }}
